
_CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION =(1 shl 0)
_CRT_INTERNAL_PRINTF_STANDARD_SNPRINTF_BEHAVIOR       =(1 shl 1)
_CRT_INTERNAL_PRINTF_LEGACY_WIDE_SPECIFIERS           =(1 shl 2)
_CRT_INTERNAL_PRINTF_LEGACY_MSVCRT_COMPATIBILITY      =(1 shl 3)
_CRT_INTERNAL_PRINTF_LEGACY_THREE_DIGIT_EXPONENTS     =(1 shl 4)
_CRT_INTERNAL_PRINTF_STANDARD_ROUNDING                =(1 shl 5)

_CRT_INTERNAL_SCANF_SECURECRT                   =(1 shl 0)
_CRT_INTERNAL_SCANF_LEGACY_WIDE_SPECIFIERS      =(1 shl 1)
_CRT_INTERNAL_SCANF_LEGACY_MSVCRT_COMPATIBILITY =(1 shl 2)
